# application.yml
spring:
  application:
    name: teleport

  r2dbc:
    url: r2dbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: wbLtktALXHIyyyweGMyEDXSJFMNmImEl

  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: wbLtktALXHIyyyweGMyEDXSJFMNmImEl
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    user: postgres
    password: wbLtktALXHIyyyweGMyEDXSJFMNmImEl

  data:
    redis:
      host: ballast.proxy.rlwy.net
      port: 57432
      username: default
      password: dnucgvNaOiiHBQjwfzqHJeCsfNsIeBIQ
      timeout: 2000ms

  webflux:
    base-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

logging:
  level:
    com.teleport.tracking: DEBUG
    org.springframework.data.r2dbc: DEBUG

---
# application-prod.yml
spring:
  config:
    activate:
      on-profile: prod

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:tracking_db}
    username: ${DB_USERNAME:tracking_user}
    password: ${DB_PASSWORD:tracking_pass}

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

logging:
  level:
    com.teleport.tracking: INFO
    org.springframework.data.r2dbc: WARN